services:
  - type: web
    name: django-myproject
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myproject-db
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "django-myproject-2.onrender.com"

databases:
  - name: myproject-db
    plan: free

